import type { Locale } from "@/i18n/config";

export interface CrudPromptInput {
  featureName: string; entityName: string; description: string; framework: string; database: string; authentication: string; uiLibrary: string; validationLibrary: string; accessPermission: string; fields: string;
  imageUpload: boolean; search: boolean; pagination: boolean; filter: boolean; sort: boolean; softDelete: boolean; auditLog: boolean; tests: boolean; rls: boolean; adminPage: boolean;
}

interface CrudCopy {
  role: string; context: string; description: string; database: string; auth: string; permission: string; fields: string; requirements: string; output: string; closing: string;
  base: string[]; imageUpload: string; search: string; pagination: string; filter: string; sort: string; softDelete: string; auditLog: string; tests: string; rls: string; adminPage: string; outputItems: string[];
}

const copies: Record<Locale, CrudCopy> = {
  vi: { role: "Bạn là Senior Full-Stack Engineer, Software Architect và UI/UX Designer. Hãy thiết kế và triển khai feature", context: "BỐI CẢNH", description: "Mô tả", database: "Cơ sở dữ liệu", auth: "Xác thực", permission: "Phân quyền", fields: "Danh sách trường", requirements: "YÊU CẦU", output: "ĐẦU RA BẮT BUỘC", closing: "Không dùng any, không hard-code secret, không bỏ qua error handling. Giải thích ngắn gọn các trade-off quan trọng.", base: ["Tạo cấu trúc thư mục rõ ràng theo Clean Architecture.", "Thiết kế schema, migration, index và ràng buộc dữ liệu phù hợp.", "Tạo CRUD API có validation đầu vào/đầu ra, phân quyền, xử lý lỗi và status code chuẩn.", "Xây dựng giao diện responsive, accessible, có loading/empty/error states."], imageUpload: "Hỗ trợ tải ảnh an toàn: validate loại/kích thước file, lưu trữ và xoá file.", search: "Có tìm kiếm với debounce và index phù hợp.", pagination: "Có phân trang phía server.", filter: "Có bộ lọc phía server.", sort: "Có sắp xếp với allowlist cột.", softDelete: "Dùng soft delete và loại trừ dữ liệu đã xoá mặc định.", auditLog: "Ghi audit log cho các thao tác thay đổi.", tests: "Viết test cho luồng thành công, validation và phân quyền.", rls: "Cấu hình Supabase Row Level Security và policy theo quyền.", adminPage: "Tạo trang quản trị để quản lý dữ liệu và phân quyền.", outputItems: ["Architecture overview và data flow", "Folder structure", "Database schema/migration và API contract", "Implementation đầy đủ theo từng file", "Security considerations", "Performance considerations", "Hướng dẫn kiểm thử và cải tiến tương lai"] },
  en: { role: "You are a Senior Full-Stack Engineer, Software Architect, and UI/UX Designer. Design and implement the feature", context: "CONTEXT", description: "Description", database: "Database", auth: "Authentication", permission: "Access permission", fields: "Field list", requirements: "REQUIREMENTS", output: "REQUIRED OUTPUT", closing: "Do not use any, do not hard-code secrets, and do not skip error handling. Briefly explain important trade-offs.", base: ["Create a clear folder structure following Clean Architecture.", "Design appropriate schema, migrations, indexes, and data constraints.", "Create CRUD APIs with input/output validation, authorization, error handling, and proper status codes.", "Build responsive, accessible UI with loading, empty, and error states."], imageUpload: "Support secure image upload: validate file type/size, store files, and remove them safely.", search: "Add search with debounce and suitable indexes.", pagination: "Add server-side pagination.", filter: "Add server-side filters.", sort: "Add sorting with an allowlist of columns.", softDelete: "Use soft delete and exclude deleted records by default.", auditLog: "Record audit logs for changing operations.", tests: "Write tests for success paths, validation, and authorization.", rls: "Configure Supabase Row Level Security and role-based policies.", adminPage: "Create an admin page to manage data and permissions.", outputItems: ["Architecture overview and data flow", "Folder structure", "Database schema/migrations and API contract", "Complete implementation by file", "Security considerations", "Performance considerations", "Testing instructions and future improvements"] },
  th: { role: "คุณเป็น Senior Full-Stack Engineer, Software Architect และ UI/UX Designer ออกแบบและพัฒนา feature", context: "บริบท", description: "คำอธิบาย", database: "ฐานข้อมูล", auth: "การยืนยันตัวตน", permission: "สิทธิ์การเข้าถึง", fields: "รายการฟิลด์", requirements: "ความต้องการ", output: "ผลลัพธ์ที่ต้องมี", closing: "ห้ามใช้ any ห้าม hard-code secret และห้ามข้าม error handling อธิบาย trade-off ที่สำคัญอย่างกระชับ", base: ["สร้างโครงสร้างโฟลเดอร์ที่ชัดเจนตาม Clean Architecture", "ออกแบบ schema, migration, index และข้อจำกัดข้อมูลที่เหมาะสม", "สร้าง CRUD API ที่มี validation อินพุต/เอาต์พุต การอนุญาต การจัดการข้อผิดพลาด และ status code ที่เหมาะสม", "สร้าง UI ที่ responsive, accessible พร้อม loading, empty และ error states"], imageUpload: "รองรับการอัปโหลดรูปอย่างปลอดภัย: ตรวจสอบชนิด/ขนาดไฟล์ จัดเก็บและลบไฟล์อย่างปลอดภัย", search: "เพิ่มการค้นหาพร้อม debounce และ index ที่เหมาะสม", pagination: "เพิ่ม pagination ฝั่ง server", filter: "เพิ่ม filter ฝั่ง server", sort: "เพิ่มการเรียงลำดับด้วย allowlist ของคอลัมน์", softDelete: "ใช้ soft delete และไม่แสดงข้อมูลที่ลบโดยปริยาย", auditLog: "บันทึก audit log สำหรับการเปลี่ยนแปลง", tests: "เขียน test สำหรับเส้นทางสำเร็จ validation และ authorization", rls: "ตั้งค่า Supabase Row Level Security และ policy ตามสิทธิ์", adminPage: "สร้างหน้า admin เพื่อจัดการข้อมูลและสิทธิ์", outputItems: ["Architecture overview และ data flow", "Folder structure", "Database schema/migration และ API contract", "Implementation ครบตามแต่ละไฟล์", "Security considerations", "Performance considerations", "แนวทางทดสอบและการปรับปรุงในอนาคต"] },
  lo: { role: "ທ່ານເປັນ Senior Full-Stack Engineer, Software Architect ແລະ UI/UX Designer. ອອກແບບ ແລະ ພັດທະນາ feature", context: "ບໍລິບົດ", description: "ຄຳອະທິບາຍ", database: "ຖານຂໍ້ມູນ", auth: "ການຢືນຢັນຕົວຕົນ", permission: "ສິດທິເຂົ້າເຖິງ", fields: "ລາຍການ field", requirements: "ຄວາມຕ້ອງການ", output: "ຜົນລັບທີ່ຕ້ອງມີ", closing: "ຫ້າມໃຊ້ any, ຫ້າມ hard-code secret ແລະ ຫ້າມຂ້າມ error handling. ອະທິບາຍ trade-off ທີ່ສຳຄັນແບບສັ້ນໆ.", base: ["ສ້າງໂຄງສ້າງ folder ທີ່ຊັດເຈນຕາມ Clean Architecture.", "ອອກແບບ schema, migration, index ແລະ ຂໍ້ຈຳກັດຂໍ້ມູນທີ່ເໝາະສົມ.", "ສ້າງ CRUD API ທີ່ມີ validation input/output, authorization, error handling ແລະ status code ທີ່ຖືກຕ້ອງ.", "ສ້າງ UI ທີ່ responsive, accessible ມີ loading, empty ແລະ error states."], imageUpload: "ຮອງຮັບການ upload ຮູບຢ່າງປອດໄພ: ກວດສອບປະເພດ/ຂະໜາດໄຟລ໌, ຈັດເກັບ ແລະ ລົບໄຟລ໌.", search: "ເພີ່ມການຄົ້ນຫາດ້ວຍ debounce ແລະ index ທີ່ເໝາະສົມ.", pagination: "ເພີ່ມ pagination ຝັ່ງ server.", filter: "ເພີ່ມ filter ຝັ່ງ server.", sort: "ເພີ່ມການຈັດລຽງດ້ວຍ allowlist ຂອງ column.", softDelete: "ໃຊ້ soft delete ແລະ ບໍ່ສະແດງຂໍ້ມູນທີ່ຖືກລົບໂດຍຄ່າເລີ່ມຕົ້ນ.", auditLog: "ບັນທຶກ audit log ສຳລັບການປ່ຽນແປງ.", tests: "ຂຽນ test ສຳລັບ success path, validation ແລະ authorization.", rls: "ຕັ້ງຄ່າ Supabase Row Level Security ແລະ policy ຕາມສິດທິ.", adminPage: "ສ້າງໜ້າ admin ເພື່ອຈັດການຂໍ້ມູນ ແລະ ສິດທິ.", outputItems: ["Architecture overview ແລະ data flow", "Folder structure", "Database schema/migration ແລະ API contract", "Implementation ຄົບຕາມແຕ່ລະໄຟລ໌", "Security considerations", "Performance considerations", "ຄຳແນະນຳການທົດສອບ ແລະ ການປັບປຸງອະນາຄົດ"] },
};

const choice = (enabled: boolean, text: string) => enabled ? text : "";

export function createCrudPrompt(input: CrudPromptInput, locale: Locale = "vi") {
  const copy = copies[locale];
  const requirements = [
    ...copy.base, choice(input.imageUpload, copy.imageUpload), choice(input.search, copy.search), choice(input.pagination, copy.pagination), choice(input.filter, copy.filter), choice(input.sort, copy.sort), choice(input.softDelete, copy.softDelete), choice(input.auditLog, copy.auditLog), choice(input.tests, copy.tests), choice(input.rls, copy.rls), choice(input.adminPage, copy.adminPage),
  ].filter(Boolean).map((item) => `- ${item}`).join("\n");
  const output = copy.outputItems.map((item, index) => `${index + 1}. ${item}`).join("\n");
  return `${copy.role} "${input.featureName.trim()}" ${locale === "vi" ? "cho entity" : locale === "th" ? "สำหรับ entity" : locale === "lo" ? "ສຳລັບ entity" : "for entity"} "${input.entityName.trim()}".\n\n${copy.context}\n- ${copy.description}: ${input.description.trim()}\n- Framework: ${input.framework}\n- ${copy.database}: ${input.database}\n- ${copy.auth}: ${input.authentication}\n- UI library: ${input.uiLibrary}\n- Validation: ${input.validationLibrary}\n- ${copy.permission}: ${input.accessPermission}\n- ${copy.fields}: ${input.fields.trim()}\n\n${copy.requirements}\n${requirements}\n\n${copy.output}\n${output}\n\n${copy.closing}`;
}
