import type { Locale } from "@/i18n/config";

export type MessageValues = Record<string, string | number>;

const en = {
  "language.label": "Language", "language.en": "English", "language.lo": "Lao", "theme.toggle": "Change theme",
  "nav.explore": "Explore", "nav.builder": "Prompt Builder", "nav.crud": "CRUD Generator", "nav.debugging": "Debugging", "nav.system": "System Check", "nav.pricing": "Pricing", "nav.login": "Log in", "nav.account": "Account", "nav.menu": "Open menu", "nav.closeMenu": "Close menu",
  "footer.description": "A platform for creating clear programming prompts for ChatGPT, Codex, Cursor, and Claude Code.", "footer.explore": "Explore", "footer.library": "Prompt library", "footer.crud": "CRUD Generator", "footer.pricing": "Pricing", "footer.information": "Information", "footer.policies": "Policies", "footer.terms": "Terms", "footer.contact": "Contact",
  "home.eyebrow": "PROMPTS FOR DEVELOPERS", "home.title": "Write better programming prompts. Ship projects faster.", "home.description": "Choose a need, enter your project information, and get a complete prompt for ChatGPT, Codex, Cursor, or Claude Code.", "home.create": "Create a prompt", "home.explore": "Explore library", "home.quickEyebrow": "GET STARTED", "home.quickTitle": "Create a CRUD prompt directly", "home.quickDescription": "No AI API required. Prompts are created safely from templates and your input.", "home.productManagement": "Product management", "home.quickCard": "Create APIs, schemas, UI, validation, and RLS from one form.", "home.openGenerator": "Open generator", "home.start": "Start", "home.categories": "Featured categories", "home.popular": "Popular prompts", "home.viewAll": "View all", "home.emptyPrompts": "No prompts have been published yet. Check back later or create your own.", "home.howItWorks": "How it works", "home.step1": "Select prompt type", "home.step2": "Enter information", "home.step3": "Get a complete prompt", "home.step4": "Copy into an AI tool", "home.cta": "Create your first prompt in under a minute.", "home.ctaDescription": "Turn an idea into a clear, implementable technical request.",
  "library.eyebrow": "LIBRARY", "library.title": "Explore prompts", "library.description": "Find prompts by task, technology, and access tier.", "library.search": "Search prompt name...", "library.allCategories": "All categories", "library.technology": "Technology", "library.access": "Free & Pro", "library.free": "Free", "library.pro": "Pro", "library.filter": "Filter", "library.newest": "Newest", "library.popular": "Popular", "library.emptyTitle": "No matching prompts", "library.emptyDescription": "Try changing your keyword or filters.", "library.previous": "Previous", "library.next": "Next",
  "card.free": "Free", "card.view": "View", "card.copy": "Copy", "toast.copied": "Prompt copied.", "toast.contentUnavailable": "Prompt content is not available yet.", "prompt.complete": "Complete prompt", "prompt.copied": "Copied", "prompt.favorite": "Save favorite", "prompt.loginToFavorite": "Log in to save favorite prompts.", "prompt.favoriteFailed": "Could not update favorite.", "prompt.favorited": "Saved to favorites.", "prompt.unfavorited": "Removed from favorites.", "detail.useCase": "Use case", "detail.instructions": "How to use", "detail.warning": "Replace the placeholders in this prompt with your real project details before using it.", "detail.copies": "copies", "detail.likes": "likes", "detail.related": "Related prompts",
  "crud.eyebrow": "PROMPT BUILDER", "crud.title": "CRUD Prompt Generator", "crud.description": "Create a CRUD implementation prompt with schema, API, UI, validation, security, and operational requirements.", "crud.configuration": "CRUD configuration", "crud.configurationDescription": "Enter details to create a structured implementation prompt.", "crud.featureName": "Feature name", "crud.entityName": "Entity", "crud.featurePlaceholder": "Example: Product management", "crud.entityPlaceholder": "Example: Product", "crud.descriptionLabel": "Feature description", "crud.descriptionPlaceholder": "Users can create, view, update, and delete products...", "crud.fields": "Field list", "crud.fieldsPlaceholder": "name: string, price: decimal, categoryId: uuid, status: enum...", "crud.framework": "Framework", "crud.database": "Database", "crud.authentication": "Authentication", "crud.permission": "Access permission", "crud.uiLibrary": "UI library", "crud.validation": "Validation", "crud.features": "Additional features", "crud.imageUpload": "Allow image upload", "crud.search": "Search", "crud.pagination": "Pagination", "crud.filter": "Filters", "crud.sort": "Sort", "crud.softDelete": "Soft delete", "crud.auditLog": "Audit log", "crud.tests": "Write tests", "crud.rls": "Supabase RLS", "crud.adminPage": "Admin page", "crud.generate": "Create CRUD prompt", "crud.outputEmpty": "Your prompt will appear here after the form is complete.", "validation.feature": "Enter a feature name.", "validation.entity": "Enter an entity name.", "validation.description": "Describe the feature in at least 10 characters.", "validation.fields": "Enter data fields.",
  "builder.task": "Task", "builder.context": "Context and requirements", "builder.taskPlaceholder": "Example: fix an OAuth login bug", "builder.contextPlaceholder": "Stack, existing code, observed error, acceptance criteria...", "builder.generate": "Create prompt", "builder.outputEmpty": "Enter a task and context to create a prompt.", "builder.title": "Prompt Builder", "builder.description": "Create a technical prompt based on your project's context.", "debugging.title": "Debugging Prompt", "debugging.description": "Create a prompt for AI to analyze the cause, propose a fix, and plan regression tests.", "system.title": "System Checking Prompt", "system.description": "Create a prompt to assess architecture, security, performance, and operations.",
  "login.title": "Admin sign in", "login.description": "Use the administrator username and password configured for this site.", "login.google": "Continue with Google", "login.redirecting": "Redirecting...", "login.missingConfig": "Supabase is not configured. Add environment variables.", "login.failed": "Could not start sign-in.", "login.username": "Username", "login.password": "Password", "login.submit": "Sign in", "login.submitting": "Signing in...", "login.invalidUsername": "Enter a valid username.", "login.invalidCredentials": "Incorrect username or password.",
  "account.title": "Your account", "account.created": "Created prompts", "account.copies": "Copy history", "account.favorites": "Favorite prompts", "account.noCreated": "No generated prompts yet.", "account.noCopies": "No copy history yet.", "account.noFavorites": "No favorite prompts yet.", "account.missingConfig": "Supabase is not configured.", "account.unavailable": "Prompt is no longer available",
  "admin.eyebrow": "ADMIN", "admin.title": "Manage prompts", "admin.description": "Publish, draft, or archive prompts in the library.", "admin.empty": "No prompts yet.", "admin.prompt": "Prompt", "admin.copyCount": "Copies", "admin.status": "Status", "admin.actions": "Actions", "admin.draft": "Draft", "admin.published": "Published", "admin.archived": "Archived", "admin.save": "Save", "admin.updated": "Status updated.", "admin.updateFailed": "Could not update prompt status.", "admin.missingConfig": "Supabase is not configured.", "admin.menu": "Admin",
  "pricing.eyebrow": "PRICING", "pricing.title": "Choose the plan that fits you", "pricing.description": "Pricing will be managed through the system before launch.", "pricing.freeTitle": "Free", "pricing.freeDescription": "Explore the prompt library and basic generators.", "pricing.proTitle": "Pro", "pricing.proDescription": "Advanced prompts, expanded history, and enhanced administration.",
  "policy.title": "Policies", "policy.p1": "DaideeAI Prompt stores only the data required to operate your account, favorites, and usage history.", "policy.p2": "Do not put secret keys in prompts or forms. Supabase Row Level Security limits access by user.", "policy.p3": "This is a baseline policy and must be reviewed by legal counsel before commercial release.", "terms.title": "Terms of use", "terms.p1": "Prompts are support tools. You are responsible for reviewing source code, security, copyright, and suitability before production use.", "terms.p2": "Do not use the service to create content that violates law, privacy, or intellectual-property rights.", "terms.p3": "These terms must be completed and approved before official operation.", "notFound.title": "Page not found", "notFound.description": "The link may have changed or the prompt is no longer published.", "notFound.back": "Back to home",
  "generator.function.title": "Function Prompt Generator", "generator.function.description": "Create implementation prompts with types, validation, tests, and error handling.", "generator.function.name": "Function name", "generator.function.purpose": "Purpose", "generator.function.inputs": "Inputs and data types", "generator.function.output": "Output and data type", "generator.function.rules": "Business rules", "generator.function.dependencies": "Dependencies", "generator.function.errors": "Error cases", "generator.function.constraints": "Security and performance constraints",
  "generator.debug.title": "Debug Prompt Generator", "generator.debug.description": "Structure incident details for root-cause analysis and safe remediation.", "generator.debug.system": "System or module", "generator.debug.expected": "Expected result", "generator.debug.actual": "Actual result", "generator.debug.logs": "Errors or logs", "generator.debug.steps": "Steps to reproduce", "generator.debug.context": "Recent changes or environment",
  "generator.system.title": "System Check Prompt Generator", "generator.system.description": "Assess system architecture, security, performance, and reliability.", "generator.system.system": "Product or system", "generator.system.architecture": "Current architecture", "generator.system.stack": "Stack and dependencies", "generator.system.data": "Data and authentication", "generator.system.scale": "Traffic or SLO", "generator.system.concerns": "Known concerns",
  "generator.create": "Create prompt", "generator.generating": "Generating...", "generator.copy": "Copy", "generator.download": "Download .txt", "generator.reset": "Reset", "generator.outputEmpty": "Your generated prompt will appear here.", "crud.defaultPermission": "Authenticated users",
  "options.framework.nextApp": "Next.js App Router", "options.framework.nextPages": "Next.js Pages Router", "options.framework.node": "Node.js", "options.framework.nest": "NestJS", "options.framework.react": "React", "options.framework.vue": "Vue", "options.framework.other": "Other", "options.database.supabase": "Supabase PostgreSQL", "options.database.postgres": "PostgreSQL", "options.database.mysql": "MySQL", "options.database.mongo": "MongoDB", "options.database.none": "None",
  "metadata.description": "Clear, reusable programming prompts for modern software projects.",
} as const;

type MessageKey = keyof typeof en;
type Messages = Record<MessageKey, string>;

const lo: Messages = {
  "language.label": "ພາສາ", "language.en": "ອັງກິດ", "language.lo": "ລາວ", "theme.toggle": "ປ່ຽນຮູບແບບ",
  "nav.explore": "ສຳຫຼວດ", "nav.builder": "ສ້າງ Prompt", "nav.crud": "ສ້າງ CRUD", "nav.debugging": "ແກ້ໄຂບັນຫາ", "nav.system": "ກວດສອບລະບົບ", "nav.pricing": "ລາຄາ", "nav.login": "ເຂົ້າລະບົບ", "nav.account": "ບັນຊີ", "nav.menu": "ເປີດເມນູ", "nav.closeMenu": "ປິດເມນູ",
  "footer.description": "ແພລດຟອມສ້າງ Prompt ສຳລັບ ChatGPT, Codex, Cursor ແລະ Claude Code.", "footer.explore": "ສຳຫຼວດ", "footer.library": "ຫໍສະໝຸດ Prompt", "footer.crud": "ຕົວສ້າງ CRUD", "footer.pricing": "ລາຄາ", "footer.information": "ຂໍ້ມູນ", "footer.policies": "ນະໂຍບາຍ", "footer.terms": "ເງື່ອນໄຂ", "footer.contact": "ຕິດຕໍ່",
  "home.eyebrow": "PROMPT ສຳລັບນັກພັດທະນາ", "home.title": "ຂຽນ Prompt ສຳລັບການຂຽນໂປຣແກຣມໃຫ້ດີຂຶ້ນ.", "home.description": "ເລືອກຄວາມຕ້ອງການ, ປ້ອນຂໍ້ມູນໂຄງການ ແລະ ຮັບ Prompt ທີ່ສົມບູນ.", "home.create": "ສ້າງ Prompt", "home.explore": "ສຳຫຼວດຫໍສະໝຸດ", "home.quickEyebrow": "ເລີ່ມຕົ້ນ", "home.quickTitle": "ສ້າງ CRUD Prompt ໂດຍກົງ", "home.quickDescription": "ບໍ່ຕ້ອງໃຊ້ AI API. Prompt ສ້າງຈາກ template ແລະ ຂໍ້ມູນຂອງທ່ານ.", "home.productManagement": "ຈັດການສິນຄ້າ", "home.quickCard": "ສ້າງ API, schema, UI, validation ແລະ RLS ຈາກແບບຟອມດຽວ.", "home.openGenerator": "ເປີດຕົວສ້າງ", "home.start": "ເລີ່ມ", "home.categories": "ໝວດໝູ່ແນະນຳ", "home.popular": "Prompt ຍອດນິຍົມ", "home.viewAll": "ເບິ່ງທັງໝົດ", "home.emptyPrompts": "ຍັງບໍ່ມີ Prompt ທີ່ເຜີຍແຜ່.", "home.howItWorks": "ວິທີໃຊ້ງານ", "home.step1": "ເລືອກປະເພດ Prompt", "home.step2": "ປ້ອນຂໍ້ມູນ", "home.step3": "ຮັບ Prompt ທີ່ສົມບູນ", "home.step4": "ຄັດລອກໄປໃຊ້ກັບເຄື່ອງມື AI", "home.cta": "ສ້າງ Prompt ທຳອິດຂອງທ່ານພາຍໃນບໍ່ເຖິງໜຶ່ງນາທີ.", "home.ctaDescription": "ປ່ຽນແນວຄິດເປັນຄຳຂໍທາງເຕັກນິກທີ່ຊັດເຈນ.",
  "library.eyebrow": "ຫໍສະໝຸດ", "library.title": "ສຳຫຼວດ Prompt", "library.description": "ຄົ້ນຫາ Prompt ຕາມວຽກ, ເຕັກໂນໂລຊີ ແລະ ລະດັບການເຂົ້າເຖິງ.", "library.search": "ຄົ້ນຫາຊື່ Prompt...", "library.allCategories": "ທຸກໝວດໝູ່", "library.technology": "ເຕັກໂນໂລຊີ", "library.access": "Free ແລະ Pro", "library.free": "ຟຣີ", "library.pro": "Pro", "library.filter": "ກັ່ນຕອງ", "library.newest": "ໃໝ່ສຸດ", "library.popular": "ຍອດນິຍົມ", "library.emptyTitle": "ບໍ່ພົບ Prompt ທີ່ກົງກັນ", "library.emptyDescription": "ລອງປ່ຽນຄຳຄົ້ນຫາ ຫຼື ຕົວກັ່ນຕອງ.", "library.previous": "ກ່ອນໜ້າ", "library.next": "ຕໍ່ໄປ",
  "card.free": "ຟຣີ", "card.view": "ເບິ່ງ", "card.copy": "ຄັດລອກ", "toast.copied": "ຄັດລອກ Prompt ແລ້ວ.", "toast.contentUnavailable": "ເນື້ອຫາ Prompt ຍັງບໍ່ພ້ອມ.", "prompt.complete": "Prompt ທີ່ສົມບູນ", "prompt.copied": "ຄັດລອກແລ້ວ", "prompt.favorite": "ບັນທຶກລາຍການມັກ", "prompt.loginToFavorite": "ກະລຸນາເຂົ້າລະບົບເພື່ອບັນທຶກ Prompt ທີ່ມັກ.", "prompt.favoriteFailed": "ບໍ່ສາມາດປັບປຸງລາຍການມັກໄດ້.", "prompt.favorited": "ບັນທຶກໃນລາຍການມັກແລ້ວ.", "prompt.unfavorited": "ລຶບອອກຈາກລາຍການມັກແລ້ວ.", "detail.useCase": "ກໍລະນີນຳໃຊ້", "detail.instructions": "ວິທີໃຊ້", "detail.warning": "ປ່ຽນ placeholder ໃນ Prompt ດ້ວຍລາຍລະອຽດໂຄງການຈິງກ່ອນໃຊ້.", "detail.copies": "ຄັ້ງທີ່ຄັດລອກ", "detail.likes": "ຖືກໃຈ", "detail.related": "Prompt ທີ່ກ່ຽວຂ້ອງ",
  "crud.eyebrow": "ຕົວສ້າງ PROMPT", "crud.title": "ຕົວສ້າງ CRUD Prompt", "crud.description": "ສ້າງ Prompt ສຳລັບພັດທະນາ CRUD ພ້ອມ schema, API, UI, validation ແລະ ຄວາມປອດໄພ.", "crud.configuration": "ຕັ້ງຄ່າ CRUD", "crud.configurationDescription": "ປ້ອນລາຍລະອຽດເພື່ອສ້າງ Prompt ທີ່ມີໂຄງສ້າງ.", "crud.featureName": "ຊື່ຟັງຊັນ", "crud.entityName": "Entity", "crud.featurePlaceholder": "ຕົວຢ່າງ: ຈັດການສິນຄ້າ", "crud.entityPlaceholder": "ຕົວຢ່າງ: Product", "crud.descriptionLabel": "ຄຳອະທິບາຍຟັງຊັນ", "crud.descriptionPlaceholder": "ຜູ້ໃຊ້ສາມາດສ້າງ, ເບິ່ງ, ແກ້ໄຂ ແລະ ລຶບສິນຄ້າ...", "crud.fields": "ລາຍການ field", "crud.fieldsPlaceholder": "name: string, price: decimal, categoryId: uuid, status: enum...", "crud.framework": "Framework", "crud.database": "ຖານຂໍ້ມູນ", "crud.authentication": "ການຢືນຢັນຕົວຕົນ", "crud.permission": "ສິດເຂົ້າເຖິງ", "crud.uiLibrary": "UI library", "crud.validation": "Validation", "crud.features": "ຟັງຊັນເພີ່ມເຕີມ", "crud.imageUpload": "ອະນຸຍາດໃຫ້ອັບໂຫຼດຮູບ", "crud.search": "ຄົ້ນຫາ", "crud.pagination": "ແບ່ງໜ້າ", "crud.filter": "ກັ່ນຕອງ", "crud.sort": "ຈັດລຽງ", "crud.softDelete": "ລຶບແບບ Soft delete", "crud.auditLog": "ບັນທຶກການກວດສອບ", "crud.tests": "ຂຽນ test", "crud.rls": "Supabase RLS", "crud.adminPage": "ໜ້າ Admin", "crud.generate": "ສ້າງ CRUD Prompt", "crud.outputEmpty": "Prompt ຂອງທ່ານຈະສະແດງຢູ່ນີ້.",
  "validation.feature": "ກະລຸນາປ້ອນຊື່ຟັງຊັນ.", "validation.entity": "ກະລຸນາປ້ອນຊື່ Entity.", "validation.description": "ກະລຸນາອະທິບາຍຟັງຊັນຢ່າງໜ້ອຍ 10 ຕົວອັກສອນ.", "validation.fields": "ກະລຸນາປ້ອນ field ຂໍ້ມູນ.",
  "builder.task": "ວຽກງານ", "builder.context": "ບໍລິບົດ ແລະ ຄວາມຕ້ອງການ", "builder.taskPlaceholder": "ຕົວຢ່າງ: ແກ້ໄຂບັນຫາການເຂົ້າລະບົບ OAuth", "builder.contextPlaceholder": "Stack, code ປັດຈຸບັນ, ຂໍ້ຜິດພາດ, ເງື່ອນໄຂການຍອມຮັບ...", "builder.generate": "ສ້າງ Prompt", "builder.outputEmpty": "ປ້ອນວຽກງານ ແລະ ບໍລິບົດເພື່ອສ້າງ Prompt.", "builder.title": "ຕົວສ້າງ Prompt", "builder.description": "ສ້າງ Prompt ດ້ານເຕັກນິກຕາມບໍລິບົດຂອງໂຄງການ.", "debugging.title": "Prompt ສຳລັບການແກ້ໄຂບັນຫາ", "debugging.description": "ສ້າງ Prompt ໃຫ້ AI ວິເຄາະສາເຫດ, ສະເໜີວິທີແກ້ ແລະ ວາງແຜນທົດສອບ.", "system.title": "Prompt ກວດສອບລະບົບ", "system.description": "ສ້າງ Prompt ເພື່ອປະເມີນ architecture, ຄວາມປອດໄພ, performance ແລະ ການດຳເນີນງານ.",
  "login.title": "ເຂົ້າລະບົບ DaideeAI Prompt", "login.description": "ໃຊ້ຊື່ຜູ້ໃຊ້ ແລະ ລະຫັດຜ່ານຂອງຜູ້ດູແລລະບົບ.", "login.google": "ດຳເນີນຕໍ່ດ້ວຍ Google", "login.redirecting": "ກຳລັງປ່ຽນໜ້າ...", "login.missingConfig": "ຍັງບໍ່ໄດ້ຕັ້ງຄ່າ Supabase.", "login.failed": "ບໍ່ສາມາດເລີ່ມເຂົ້າລະບົບໄດ້.", "login.username": "ຊື່ຜູ້ໃຊ້", "login.password": "ລະຫັດຜ່ານ", "login.submit": "ເຂົ້າລະບົບ", "login.submitting": "ກຳລັງເຂົ້າລະບົບ...", "login.invalidUsername": "ຊື່ຜູ້ໃຊ້ບໍ່ຖືກຕ້ອງ.", "login.invalidCredentials": "ຊື່ຜູ້ໃຊ້ ຫຼື ລະຫັດຜ່ານບໍ່ຖືກຕ້ອງ.",
  "account.title": "ບັນຊີຂອງທ່ານ", "account.created": "Prompt ທີ່ສ້າງ", "account.copies": "ປະຫວັດການຄັດລອກ", "account.favorites": "Prompt ທີ່ມັກ", "account.noCreated": "ຍັງບໍ່ມີ Prompt ທີ່ສ້າງ.", "account.noCopies": "ຍັງບໍ່ມີປະຫວັດການຄັດລອກ.", "account.noFavorites": "ຍັງບໍ່ມີ Prompt ທີ່ມັກ.", "account.missingConfig": "ຍັງບໍ່ໄດ້ຕັ້ງຄ່າ Supabase.", "account.unavailable": "Prompt ບໍ່ພ້ອມໃຊ້ແລ້ວ",
  "admin.eyebrow": "ຜູ້ດູແລລະບົບ", "admin.title": "ຈັດການ Prompt", "admin.description": "ເຜີຍແຜ່, ຮ່າງ ຫຼື ເກັບ Prompt ໃນຫໍສະໝຸດ.", "admin.empty": "ຍັງບໍ່ມີ Prompt.", "admin.prompt": "Prompt", "admin.copyCount": "ຈຳນວນຄັດລອກ", "admin.status": "ສະຖານະ", "admin.actions": "ການດຳເນີນການ", "admin.draft": "ຮ່າງ", "admin.published": "ເຜີຍແຜ່", "admin.archived": "ເກັບໄວ້", "admin.save": "ບັນທຶກ", "admin.updated": "ອັບເດດສະຖານະແລ້ວ.", "admin.updateFailed": "ບໍ່ສາມາດອັບເດດສະຖານະ Prompt ໄດ້.", "admin.missingConfig": "ຍັງບໍ່ໄດ້ຕັ້ງຄ່າ Supabase.", "admin.menu": "Admin",
  "pricing.eyebrow": "ລາຄາ", "pricing.title": "ເລືອກແຜນທີ່ເໝາະກັບທ່ານ", "pricing.description": "ລາຄາຈະຖືກຈັດການຜ່ານລະບົບກ່ອນເປີດໃຊ້ງານ.", "pricing.freeTitle": "ຟຣີ", "pricing.freeDescription": "ສຳຫຼວດຫໍສະໝຸດ Prompt ແລະ ຕົວສ້າງພື້ນຖານ.", "pricing.proTitle": "Pro", "pricing.proDescription": "Prompt ຂັ້ນສູງ ແລະ ຄວາມສາມາດການຈັດການເພີ່ມເຕີມ.",
  "policy.title": "ນະໂຍບາຍ", "policy.p1": "DaideeAI Prompt ເກັບຮັກສາພຽງຂໍ້ມູນທີ່ຈຳເປັນສຳລັບບັນຊີ, ລາຍການມັກ ແລະ ປະຫວັດການໃຊ້ງານ.", "policy.p2": "ຢ່າໃສ່ secret key ໃນ Prompt ຫຼື ແບບຟອມ. Supabase Row Level Security ຈຳກັດການເຂົ້າເຖິງ.", "policy.p3": "ນີ້ແມ່ນນະໂຍບາຍເບື້ອງຕົ້ນ ແລະ ຄວນໃຫ້ທີ່ປຶກສາກົດໝາຍກວດສອບກ່ອນນຳໃຊ້ເຊີງພານິດ.", "terms.title": "ເງື່ອນໄຂການໃຊ້", "terms.p1": "Prompt ແມ່ນເຄື່ອງມືຊ່ວຍ. ທ່ານຕ້ອງກວດສອບ source code, ຄວາມປອດໄພ, ລິຂະສິດ ແລະ ຄວາມເໝາະສົມກ່ອນນຳໄປໃຊ້ໃນ production.", "terms.p2": "ຫ້າມໃຊ້ບໍລິການເພື່ອສ້າງເນື້ອຫາທີ່ລະເມີດກົດໝາຍ, ຄວາມເປັນສ່ວນຕົວ ຫຼື ສິດທາງປັນຍາ.", "terms.p3": "ເງື່ອນໄຂນີ້ຕ້ອງຖືກທົບທວນ ແລະ ອະນຸມັດກ່ອນເປີດໃຊ້ງານຢ່າງເປັນທາງການ.", "notFound.title": "ບໍ່ພົບໜ້າ", "notFound.description": "ລິ້ງອາດຖືກປ່ຽນ ຫຼື Prompt ບໍ່ໄດ້ເຜີຍແຜ່ແລ້ວ.", "notFound.back": "ກັບໜ້າຫຼັກ",
  "generator.function.title": "ຕົວສ້າງ Function Prompt", "generator.function.description": "ສ້າງ Prompt ສຳລັບການພັດທະນາ ພ້ອມ type, validation, test ແລະ error handling.", "generator.function.name": "ຊື່ Function", "generator.function.purpose": "ຈຸດປະສົງ", "generator.function.inputs": "Input ແລະ ປະເພດຂໍ້ມູນ", "generator.function.output": "Output ແລະ ປະເພດຂໍ້ມູນ", "generator.function.rules": "ກົດທຸລະກິດ", "generator.function.dependencies": "Dependencies", "generator.function.errors": "ກໍລະນີຂໍ້ຜິດພາດ", "generator.function.constraints": "ຂໍ້ຈຳກັດດ້ານຄວາມປອດໄພ ແລະ performance",
  "generator.debug.title": "ຕົວສ້າງ Debug Prompt", "generator.debug.description": "ຈັດໂຄງສ້າງລາຍລະອຽດເຫດການເພື່ອວິເຄາະສາເຫດ ແລະ ແກ້ໄຂຢ່າງປອດໄພ.", "generator.debug.system": "ລະບົບ ຫຼື module", "generator.debug.expected": "ຜົນທີ່ຄາດຫວັງ", "generator.debug.actual": "ຜົນທີ່ເກີດຂຶ້ນຈິງ", "generator.debug.logs": "ຂໍ້ຜິດພາດ ຫຼື log", "generator.debug.steps": "ຂັ້ນຕອນທີ່ເຮັດໃຫ້ເກີດບັນຫາ", "generator.debug.context": "ການປ່ຽນແປງຫຼ້າສຸດ ຫຼື environment",
  "generator.system.title": "ຕົວສ້າງ System Check Prompt", "generator.system.description": "ປະເມີນ architecture, ຄວາມປອດໄພ, performance ແລະ ຄວາມໜ້າເຊື່ອຖື.", "generator.system.system": "ຜະລິດຕະພັນ ຫຼື ລະບົບ", "generator.system.architecture": "Architecture ປັດຈຸບັນ", "generator.system.stack": "Stack ແລະ dependencies", "generator.system.data": "ຂໍ້ມູນ ແລະ ການຢືນຢັນຕົວຕົນ", "generator.system.scale": "Traffic ຫຼື SLO", "generator.system.concerns": "ຂໍ້ກັງວົນທີ່ຮູ້ແລ້ວ",
  "generator.create": "ສ້າງ Prompt", "generator.generating": "ກຳລັງສ້າງ...", "generator.copy": "ຄັດລອກ", "generator.download": "ດາວໂຫຼດ .txt", "generator.reset": "ລ້າງຄ່າ", "generator.outputEmpty": "Prompt ທີ່ສ້າງຈະສະແດງຢູ່ນີ້.", "crud.defaultPermission": "ຜູ້ໃຊ້ທີ່ຢືນຢັນແລ້ວ",
  "options.framework.nextApp": "Next.js App Router", "options.framework.nextPages": "Next.js Pages Router", "options.framework.node": "Node.js", "options.framework.nest": "NestJS", "options.framework.react": "React", "options.framework.vue": "Vue", "options.framework.other": "ອື່ນໆ", "options.database.supabase": "Supabase PostgreSQL", "options.database.postgres": "PostgreSQL", "options.database.mysql": "MySQL", "options.database.mongo": "MongoDB", "options.database.none": "ບໍ່ມີ",
  "metadata.description": "Prompt ສຳລັບການຂຽນໂປຣແກຣມທີ່ຊັດເຈນ ແລະ ນຳກັບມາໃຊ້ໄດ້ສຳລັບໂຄງການຊອບແວສະໄໝໃໝ່.",
};

export const messages: Record<Locale, Messages> = { en, lo };

export function translate(locale: Locale, key: MessageKey, values?: MessageValues) {
  const template = messages[locale][key] ?? en[key];
  if (!values) return template;
  return template.replace(/\{(\w+)\}/g, (_, name: string) => String(values[name] ?? `{${name}}`));
}

export type { MessageKey };
